# Generated by Django 4.2.3 on 2024-06-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeannanApps', '0004_products_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='HomeProducts',
        ),
        migrations.AlterModelOptions(
            name='homeproducts',
            options={'verbose_name': 'HomeProduct', 'verbose_name_plural': 'HomeProducts'},
        ),
    ]
