# Generated by Django 4.2.3 on 2024-06-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeannanApps', '0007_alter_shop_options_remove_contactus_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
