# Generated by Django 4.2.3 on 2024-06-11 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("MeannanApps", "0008_alter_contactus_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="product_price",
        ),
        migrations.CreateModel(
            name="ProductVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=50)),
                ("price", models.FloatField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MeannanApps.shop",
                    ),
                ),
            ],
        ),
    ]
