# Generated by Django 4.2.3 on 2024-06-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MeannanApps", "0009_remove_shop_product_price_productvariation"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariation",
            name="quantity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
