# Generated by Django 4.2.3 on 2024-06-11 23:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MeannanApps", "0010_productvariation_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productvariation",
            old_name="size",
            new_name="weight",
        ),
    ]
