# Generated by Django 4.2.3 on 2024-06-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MeannanApps", "0011_rename_size_productvariation_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="product_price",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
