# Generated by Django 4.2.3 on 2024-06-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MeannanApps", "0014_cartitem_product_variant_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="headers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
