# Generated by Django 4.2.3 on 2024-06-12 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MeannanApps", "0015_cart_headers_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="headers",
        ),
    ]
