# Generated by Django 4.2.3 on 2024-06-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MeannanApps", "0016_remove_cart_headers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
