# Generated by Django 4.2.3 on 2024-06-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MeannanApps", "0017_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billingaddress",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="billingaddress",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="billingaddress",
            name="town_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
